<?xml version="1.0" encoding="ISO-8859-1"?>

<bugs>
	<bug>
		<id>411</id>
		<title>Команда clients некорректно отображает ip за reverse-proxy</title>
		<body>При работе в dev окружении в логе отображается корректный ip игрока, однако, clients всё равно отображает 127.0.0.1</body>
		<created>2020-08-22 12:10:51</created>
		<closed>2020-08-24 09:15:50</closed>
	</bug>
	<bug>
		<id>388</id>
		<title>Недостаток зависимости ClientLaunchCore</title>
		<body>java.lang.RuntimeException: Module DiscordRPC required ClientLauncherCore. ClientLauncherCore not found at pro.gravit.launcher.AbodeOFleGENDs.ABOdEOfLEGends(Unknown Source) at pro.gravit.launcher.AbodeOFleGENDs.aBOdEoFLeGends(Unknown Source)  5.1.5-dev.</body>
		<created>2020-05-01 09:59:05</created>
		<closed>2020-05-01 16:57:37</closed>
	</bug>
	<bug>
		<id>387</id>
		<title>Команда unindexasset работает не правильно</title>
		<body>При использовании команды `unindexasset` происходит разындексирование папки ассетов, с этой стороны все нормально, но когда приходит время использовать команду `indexasset` выдаёт ошибки ``` [INFO]  Creating indexed asset dir: 'asset1.12' [ERROR] java.nio.file.FileAlreadyExistsException: /launchserver/updates/asset1.12 ``` Из чего можно сделать вывод, что разындексированная папка не удаляется, хотя команда `indexasset` подразумевает это</body>
		<created>2020-04-26 07:50:04</created>
		<closed>2020-04-26 14:52:38</closed>
	</bug>
	<bug>
		<id>383</id>
		<title>Исправления runtime</title>
		<body>8. Для сцены servermenu использовать кастомный serverImage-фон. Для каждого игрового сервера своя фоновая картинка.  5. Исправление заголовка названия функции (размер шрифта) и описания функции, это относится к элементам в сценах settings и options ![image](https://user-images.githubusercontent.com/45002341/80211032-8b838200-863d-11ea-8498-84c166cf60ba.png) </body>
		<created>2020-04-24 12:09:25</created>
		<closed>2020-04-24 12:40:08</closed>
	</bug>
	<bug>
		<id>380</id>
		<title>Баг запуска клиента</title>
		<body>Существует кратковременный запуск дебаг-окна при запуске клиента, даже если режим дебага отключен.</body>
		<created>2020-04-24 12:03:12</created>
		<closed>2020-04-24 12:38:23</closed>
	</bug>
	<bug>
		<id>344</id>
		<title>Криво работает "Сменить директорию загрузки"</title>
		<body>Нажимаем кнопку "Сменить директорию загрузки", выбираем новую директорию, в модальном окне нажимаем кнопку "Да, перенести!" получаем ошибку https://pastebin.com/SfdGY1mk ошибка будет повторяться при каждом нажатии кнопки пока не нажмем кнопку "Нет не нужно".  Нажимаем кнопку "Нет не нужно", повторно проделываем все действия и только тогда перенос срабатывает. Тестировалось на дефолтном рантайме, версия последняя собранная из исходников.</body>
		<created>2019-10-18 06:30:41</created>
		<closed>2020-04-18 09:31:22</closed>
	</bug>
	<bug>
		<id>340</id>
		<title>Отсутствуют сообщения в рантайме при скачивании zip-архивом</title>
		<body>При настройке bindings в конфиге лаунчсервера, рантайм не знает о загрузке zip архива и отображает 0% загрузки, но скачивание и распаковка идут (судя по дебагу). Версия 5.0.10 dev</body>
		<created>2019-10-09 02:12:25</created>
		<closed>2020-04-14 12:39:19</closed>
	</bug>
	<bug>
		<id>337</id>
		<title>Краш на 1.14.4</title>
		<body>Собрал клиент Fabric 1.14, но с гравитом он работает некорректно. С теми же либами на Tlauncher/MultiMC/Mojang все работает.  Логи с фабрика -- https://paste.dimdev.org/tosocenode.hs Логи с ванили 1.14 -- https://paste.dimdev.org/nefudopifa.sql  *** # Как повторить  * Заходишь на 1.14.4 * Заходишь в локальный мир * Жмём сделать скриншот (F2) * Нажимаем по названию скриншота * _вылет_ **Должно открывать сам файл скриншота**</body>
		<created>2019-09-24 05:09:27</created>
		<closed>2019-09-24 17:18:20</closed>
	</bug>
	<bug>
		<id>285</id>
		<title>Не отображаются updateOptional с permissions:1</title>
		<body>Не отображается updateOptional c permissions:1</body>
		<created>2019-06-17 08:39:14</created>
		<closed>2019-06-17 10:08:04</closed>
	</bug>
	<bug>
		<id>284</id>
		<title>Баг в pro.gravit.launcher.client.ClientLauncher.launch()</title>
		<body>Вкратце: Если метод main принимает varargs, а не массив, то происходит краш, типа нельзя прикастовать [Ljava/lang/String; в String Особенно мешает этот баг при использовании ModLauncher вместо LaunchWrapper (приходится писать обёртку), что необходимо при использовании Forge на версии 1.13.2</body>
		<created>2019-06-13 21:57:42</created>
		<closed>2019-06-14 10:28:31</closed>
	</bug>
	<bug>
		<id>275</id>
		<title>Противный баг GUI опциональных модов</title>
		<body>При включении/отключении опциональных модов - обновляется и откидывает на верх. ![WiW8J1lvSl](https://user-images.githubusercontent.com/18057310/58387618-ba4e3e00-8011-11e9-9fe5-7d6a52299985.gif) </body>
		<created>2019-05-26 22:03:55</created>
		<closed>2019-05-28 13:10:18</closed>
	</bug>
	<bug>
		<id>263</id>
		<title>Закрытие лаунчсервер cntrl + c</title>
		<body>При закрытии лаунчерсервера cntrl + c приходиться 2 раза cntrl + c нажимать. чтобы закрыть лаунчер. при cntrl + a + d вообще зависает лаунчер.</body>
		<created>2019-05-19 19:07:43</created>
		<closed>2019-05-21 22:57:34</closed>
	</bug>
	<bug>
		<id>262</id>
		<title>Не работает индикация при загрузке zip</title>
		<body>Я написал чтобы вы вспомнили, что не работает индикация при загрузке zip ![unknown](https://user-images.githubusercontent.com/32196950/57982263-8b512e80-7a4b-11e9-807c-acc256bd3799.png) </body>
		<created>2019-05-19 12:39:23</created>
		<closed>2019-05-21 00:42:30</closed>
	</bug>
	<bug>
		<id>256</id>
		<title>[DEV] Ошибка при экстренном завершение приложения</title>
		<body>При нажатии CTRL + C такая ошибка:  ``` Exception in thread "Command Thread" org.jline.reader.UserInterruptException         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:648)         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:395)         at ru.gravit.utils.command.JLineCommandHandler.readLine(JLineCommandHandler.java:77)         at ru.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:99)         at ru.gravit.utils.command.CommandHandler.run(CommandHandler.java:129)         at java.lang.Thread.run(Thread.java:748) ```</body>
		<created>2019-05-11 17:53:29</created>
		<closed>2019-05-14 09:09:47</closed>
	</bug>
	<bug>
		<id>241</id>
		<title>Hwid Bug (type: json)</title>
		<body>2019.05.02 23:35:26 [ERROR] java.lang.NullPointerException at ru.gravit.launchserver.auth.hwid.JsonHWIDHandler.check0(JsonHWIDHandler.java:100) at ru.gravit.launchserver.auth.hwid.HWIDHandler.check(HWIDHandler.java:27) at ru.gravit.launchserver.websocket.json.auth.AuthResponse.execute(AuthResponse.java:107) at ru.gravit.launchserver.websocket.WebSocketService.process(WebSocketService.java:69) at ru.gravit.launchserver.websocket.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:45) at ru.gravit.launchserver.websocket.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:16) at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:77) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler$1.channelRead(WebSocketServerProtocolHandler.java:211) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748)</body>
		<created>2019-05-02 21:37:55</created>
		<closed>2019-05-04 00:47:21</closed>
	</bug>
	<bug>
		<id>228</id>
		<title>Лаунчер не сохраняет настройки</title>
		<body>На версии 4.5.0 перестали сохраняться настройки. Через несколько запусков тупо требуется авторизация снова, по логам - лаунчер не может прочитать файл настроек.  Баг ловится через раз, как только снова поймаю - отправлю точные логи. Точнее - логин/пароль сбрасываются, и при каждом заходе в настройки лаунчера, дебаг чекбокс становится чекнутым, даже если его анчекнуть и снова перезапустить лаунчер. С настройкой смены папки аналогичная проблема.</body>
		<created>2019-04-19 22:35:37</created>
		<closed>2019-04-26 00:55:43</closed>
	</bug>
	<bug>
		<id>219</id>
		<title>Куча лишнего кода в RequestAuthHandler.</title>
		<body></body>
		<created>2019-04-12 14:45:17</created>
		<closed>2019-04-12 20:22:49</closed>
	</bug>
	<bug>
		<id>211</id>
		<title>4.5.0 игнорирует Update Exclusions</title>
		<body>![изображение](https://user-images.githubusercontent.com/3335371/55648448-8cffc380-580a-11e9-9559-e6b14766a872.png)  `2019.04.06 01:19:52 [ERROR] java.lang.SecurityException: Forbidden modification (ENTRY_CREATE, 1 times): '...\mods\OpenTerrainGenerator' at ...`</body>
		<created>2019-04-05 18:23:55</created>
		<closed>2019-04-10 08:59:39</closed>
	</bug>
	<bug>
		<id>208</id>
		<title>Ошибка при запуске клиента</title>
		<body>2019.04.04 20:27:56 [ERROR] java.lang.AssertionError: AssertionError (GSON 2.8.5): java.lang.NoSuchFieldException: SERVER         at com.google.gson.Gson.toJson(Unknown Source)         at com.google.gson.Gson.toJson(Unknown Source)         at com.google.gson.Gson.toJson(Unknown Source)         at ru.gravit.launcher.teCHna.teCHNG(Unknown Source)         at ru.gravit.launcher.tEchOK.TEchXp(Unknown Source)         at ru.gravit.launcher.TEchZT.TEchXp(Unknown Source)         at ru.gravit.launcher.TEchZT.TEchXp(Unknown Source)         at ru.gravit.launcher.TEchqH.request(Unknown Source)         at jdk.nashorn.internal.scripts.Script$Recompilation$69$2936$\^eval\_.newRequestTask#L:80(&lt;eval&gt;:80)         at javafx.concurrent.Task$$NashornJavaAdapter.call(Unknown Source)         at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)         at java.util.concurrent.FutureTask.run(Unknown Source)         at javafx.concurrent.Task$$NashornJavaAdapter.run(Unknown Source)         at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)         at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)         at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)         at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: SERVER         at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.&lt;init&gt;(Unknown Source)         at com.google.gson.internal.bind.TypeAdapters$30.create(Unknown Source)         at com.google.gson.Gson.getAdapter(Unknown Source)         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(Unknown Source)         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(Unknown Source)         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(Unknown Source)         at com.google.gson.Gson.getAdapter(Unknown Source)         at com.google.gson.Gson.toJson(Unknown Source)         at com.google.gson.Gson.toJsonTree(Unknown Source)         at com.google.gson.Gson.toJsonTree(Unknown Source)         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(Unknown Source)         at ru.gravit.launcher.TEChue.TEchXp(Unknown Source)         at ru.gravit.launcher.TEChue.serialize(Unknown Source)         at com.google.gson.internal.bind.TreeTypeAdapter.write(Unknown Source)         ... 18 more Caused by: java.lang.NoSuchFieldException: SERVER         at java.lang.Class.getField(Unknown Source)         ... 32 more</body>
		<created>2019-04-04 15:31:38</created>
		<closed>2019-04-06 08:44:08</closed>
	</bug>
	<bug>
		<id>201</id>
		<title>Suppressed: java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF</title>
		<body>Modulea jarsigner 2019.03.26 21:27:16 [ERROR] java.lang.NullPointerException         at ru.gravit.launchermodules.jarsigner.SignJarTask.process(SignJarTask.java:40)         at ru.gravit.launchserver.binary.JARLauncherBinary.build(JARLauncherBinary.java:63)         at ru.gravit.launchserver.LaunchServer.buildLauncherBinaries(LaunchServer.java:605)         at ru.gravit.launchserver.command.basic.BuildCommand.invoke(BuildCommand.java:23)         at ru.gravit.utils.command.CommandHandler.eval(CommandHandler.java:41)         at ru.gravit.utils.command.CommandHandler.eval(CommandHandler.java:30)         at ru.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:69)         at ru.gravit.utils.command.CommandHandler.run(CommandHandler.java:82)         at java.lang.Thread.run(Thread.java:748)         Suppressed: java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF                 at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)                 at ru.gravit.launchermodules.jarsigner.SignerJar.writeManifest(SignerJar.java:367)                 at ru.gravit.launchermodules.jarsigner.SignerJar.finish(SignerJar.java:290)                 at ru.gravit.launchermodules.jarsigner.SignerJar.close(SignerJar.java:257)                 at ru.gravit.launchermodules.jarsigner.SignJarTask.process(SignJarTask.java:43)                 ... 8 more jarsigner module</body>
		<created>2019-03-27 08:55:30</created>
		<closed>2019-03-28 08:54:45</closed>
	</bug>
	<bug>
		<id>189</id>
		<title>Вызов несуществующего (удалённого) метода в JAConfigurator</title>
		<body>https://github.com/GravitLauncher/Launcher/blob/7050e0e9ac8b65f09147b1f38a24b08539a9309c/libLauncher/src/main/java/ru/gravit/launcher/modules/ModulesManager.java#L24  https://github.com/GravitLauncher/Launcher/blob/7050e0e9ac8b65f09147b1f38a24b08539a9309c/LaunchServer/src/main/java/ru/gravit/launchserver/binary/JAConfigurator.java#L37-L39  Сломано в #153 </body>
		<created>2019-03-10 08:46:12</created>
		<closed>2019-03-10 09:19:07</closed>
	</bug>
	<bug>
		<id>185</id>
		<title>Баг опциональных модов #5</title>
		<body>![llqxlbdsjo](https://user-images.githubusercontent.com/18057310/53688704-aebfe380-3d50-11e9-91ff-09e1a2001bb7.gif) Версия лаунчера - dev (Последний билд на момент публикации данной проблемы со всеми патчами) Описание проблемы: При отключении хоть одной модификации, которая зависит от какой ни будь - отключаются сразу все также зависящие от неё. </body>
		<created>2019-03-02 23:14:00</created>
		<closed>2019-03-03 09:36:48</closed>
	</bug>
	<bug>
		<id>179</id>
		<title>4.3.1.1 Update не выполняет своей функции.</title>
		<body>Есть настройка в профайле с таким содержимым `"update": [     "config/ImmersiveEngineering.cfg",     "config/GalacticraftAmunRa.cfg",     "config/ExtraPlanets.cfg",     "config/MorePlanets.cfg",     "config/GalaxySpace/core.conf",     "config/ic2/blast_furnace.ini",     "config/ic2/block_cutter.ini",     "config/ic2/compressor.ini",     "config/ic2/extractor.ini",     "config/ic2/macerator.ini",     "config/ic2/metal_former_cutting.ini",     "config/ic2/metal_former_extruding.ini",     "config/ic2/metal_former_rolling.ini",     "config/ic2/ore_washer.ini",     "config/ic2/thermal_centrifuge.ini",     "config/ic2/uu_scan_values.ini",     "servers.dat"   ],   "updateExclusions": [     "mods/VoxelMods",     "mods/railcraft",     "mods/ic2"         ],   "updateShared": [],   "updateVerify": [     "libraries",     "natives",     "mods",     "minecraft.jar",     "forge.jar",     "liteloader.jar"   ], ` Из этой настройки следует, что лаунчер при запуске клиента должен перекачать файлы, которые указаны в update[]; На деле же происходит следующие. При первом (холодном) запуске лаунчера, он докачивает эти файлы. Но этот файл может мной изменяться и после изменения происходит syncUpdates. На втором запуске, лаунчер проверяет НАЛИЧИЕ этого файла в той директории которую я указал. Но вот Он не перекачивает его. Хотя функция Update как раз должна перекачивать файл каждый раз при старте клиента. </body>
		<created>2019-02-23 20:37:39</created>
		<closed>2019-02-24 13:29:23</closed>
	</bug>
	<bug>
		<id>176</id>
		<title>LaunchServer v4.3.3-2 dev ветка ошибка при сохранении settings.bin (несогласованность чтения/записи)</title>
		<body>При первом старте лаунчера все ок. Далее после игровой сессии и закрытии лаунчера, повторный запуск оборачивается ошибкой. `2019.02.20 19:40:43 [ERROR] java.lang.RuntimeException: Exception in Application init method         at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:912)         at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)         at java.lang.Thread.run(Unknown Source) Caused by: java.lang.IllegalArgumentException: Invalid file name: '     forge.ja'         at ru.gravit.utils.helper.VerifyHelper.verify(Unknown Source)         at ru.gravit.utils.helper.IOHelper.verifyFileName(Unknown Source)         at ru.gravit.launcher.client.LauncherSettings.read(Unknown Source)         at ru.gravit.launcher.client.LauncherSettings$$NashornJavaAdapter.read(Unknown Source)         at ru.gravit.launcher.client.LauncherSettings.load(Unknown Source)         at ru.gravit.launcher.client.LauncherSettings$$NashornJavaAdapter.load(Unknown Source)         at jdk.nashorn.internal.scripts.Script$Recompilation$4$190$\^eval\_.init(&lt;eval&gt;:9)         at ru.gravit.launcher.JSApplication$$NashornJavaAdapter.init(Unknown Source)         at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)         ... 2 more` При удалении options и settings все запускается. Гравит уже правил тут :   https://github.com/GravitLauncher/Launcher/commit/a738f7566737ba017b94de4c91411c1ef5e93358 https://github.com/GravitLauncher/Launcher/commit/66f773a8cef89baf83e8b70b2b1ba76431a2cf43 https://github.com/GravitLauncher/Launcher/commit/5d77b9c53ab9153ad1c41b256d6b7bb7245224c8 https://github.com/GravitLauncher/Launcher/commit/67b88bc5938365726258fc85be7352a91cc1cc7b https://github.com/GravitLauncher/Launcher/commit/fc21e854d3d22f0b316af99ffa2a819c1dd54d7a  Осталось решить вопрос с повторным запуском лаунчера.</body>
		<created>2019-02-21 18:41:49</created>
		<closed>2019-02-23 11:13:57</closed>
	</bug>
	<bug>
		<id>170</id>
		<title>Ошибка проверки обновления Версия 4.3.1.1</title>
		<body>`2019.02.11 11:31:14 [ERROR] org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/GravitLauncher/Launcher/releases/latest         at org.kohsuke.github.Requester.parse(Requester.java:646)         at org.kohsuke.github.Requester.parse(Requester.java:607)         at org.kohsuke.github.Requester._to(Requester.java:285)         at org.kohsuke.github.Requester.to(Requester.java:247)         at org.kohsuke.github.GHRepository.getLatestRelease(GHRepository.java:331)         at ru.gravit.launchserver.Updater.run(Updater.java:46)         at java.util.TimerThread.mainLoop(Unknown Source)         at java.util.TimerThread.run(Unknown Source) Caused by: java.net.UnknownHostException: api.github.com         at java.net.AbstractPlainSocketImpl.connect(Unknown Source)         at java.net.PlainSocketImpl.connect(Unknown Source)         at java.net.SocksSocketImpl.connect(Unknown Source)         at java.net.Socket.connect(Unknown Source)         at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)         at sun.net.NetworkClient.doConnect(Unknown Source)         at sun.net.www.http.HttpClient.openServer(Unknown Source)         at sun.net.www.http.HttpClient.openServer(Unknown Source)         at sun.net.www.protocol.https.HttpsClient.&lt;init&gt;(Unknown Source)         at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)         at java.net.HttpURLConnection.getResponseCode(Unknown Source)         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)         at org.kohsuke.github.Requester.parse(Requester.java:615)         ... 7 more`</body>
		<created>2019-02-12 20:32:45</created>
		<closed>2019-02-13 05:36:21</closed>
	</bug>
	<bug>
		<id>165</id>
		<title>Опциональные моды</title>
		<body>Не сохраняются опциональные моды.</body>
		<created>2019-02-02 12:44:31</created>
		<closed>2019-02-05 12:34:11</closed>
	</bug>
	<bug>
		<id>150</id>
		<title>Команда restart не работает</title>
		<body>В общем, на последнем релизе 4,2.1 нельзя испольовать команду рестарт, появляетсяо шбика:  restart 2019.01.15 21:58:29 [INFO] Command 'restart' 2019.01.15 21:58:29 [ERROR] java.lang.ArrayIndexOutOfBoundsException: 0  Приходится полностью останавливать лаунчсервер  запускать его с нуля</body>
		<created>2019-01-15 22:01:34</created>
		<closed>2019-01-16 08:48:49</closed>
	</bug>
	<bug>
		<id>133</id>
		<title>Не собирает indexAsset </title>
		<body>При выполнении команд 1. unindexAsset asset1.7.10 1.7.10 unindexed  2. удаляете asset1.7.10  3. в unindexed/icons и unindexed/minecraft/icons меняете иконки  4. и потом indexAsset unindexed 1.7.10 asset1.7.10  5. удаляете unindexed Не собирает и выдает ошибку В старом Сашке все ок. https://hastebin.com/socipareke.rb</body>
		<created>2019-01-08 23:35:58</created>
		<closed>2019-01-08 23:48:23</closed>
	</bug>
	<bug>
		<id>111</id>
		<title>Добавить в autogenConfig md5 config.bin.</title>
		<body>Для улучшения защиты от подмены рантайма.</body>
		<created>2018-12-26 15:19:27</created>
		<closed>2018-12-29 10:39:55</closed>
	</bug>
	<bug>
		<id>107</id>
		<title>Modules: проверить порядок работы.</title>
		<body>Возможно исправить preInit на loadModule (есть такое подозрение).</body>
		<created>2018-12-18 13:51:15</created>
		<closed>2018-12-19 16:22:11</closed>
	</bug>
	<bug>
		<id>99</id>
		<title>Баг с BuildContext</title>
		<body>https://github.com/GravitLauncher/Launcher/edit/master/LaunchServer/src/main/java/ru/gravit/launchserver/binary/BuildContext.java он аналогичен багу с JarLauncherBinary, фиксится пересозданием entry.</body>
		<created>2018-12-10 12:27:09</created>
		<closed>2018-12-14 13:58:22</closed>
	</bug>
	<bug>
		<id>91</id>
		<title>IndexOutOfBoundsException в runtime</title>
		<body>Проблема возникла при удалении одного из профайлов, в результате var settings.profile у некоторых игроков стал больше, чем profiles.length  https://github.com/GravitLauncher/Launcher/blob/ed7a09d2234c757dd9140d3314b3a9fbb1f5ed29/Launcher/runtime/dialog/dialog.js#L297  `Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 3, Size: 3         at java.util.ArrayList.rangeCheck(Unknown Source)         at java.util.ArrayList.get(Unknown Source)         at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)         at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)         at jdk.nashorn.internal.scripts.Script$Recompilation$85$9736A$^eval_.updateProfilesList(&lt;eval&gt;:297)         at jdk.nashorn.internal.scripts.Script$Recompilation$80$6642A$^eval_.verifyLauncher#L:192#L:192#L:199#L:199(&lt;eval&gt;:203)         at jdk.nashorn.internal.scripts.Script$Recompilation$72$1768A$^eval_.setTaskProperties#L:44(&lt;eval&gt;:47)         at javafx.event.EventHandler$$NashornJavaAdapter.handle(Unknown Source)         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)         at javafx.event.Event.fireEvent(Event.java:198)         at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)         at javafx.concurrent.Task.fireEvent(Task.java:1356)         at javafx.concurrent.Task.setState(Task.java:723)         at javafx.concurrent.Task$TaskCallable.lambda$call$501(Task.java:1434)         at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)         at java.security.AccessController.doPrivileged(Native Method)         at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)         at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)         at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)         at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)         at java.lang.Thread.run(Unknown Source)`</body>
		<created>2018-12-02 18:23:59</created>
		<closed>2018-12-14 13:58:55</closed>
	</bug>
	<bug>
		<id>89</id>
		<title>ClientLauncher.verifyHDir is not a function</title>
		<body>https://github.com/GravitLauncher/Launcher/blob/v4.1.x/Launcher/runtime/dialog/overlay/update/update.js#L81  verifyHDir выброшен из API с коммита https://github.com/GravitLauncher/Launcher/commit/c95e3ff2329ef9949d36fd0380b4f0efba60e09f</body>
		<created>2018-11-30 18:17:33</created>
		<closed>2018-12-03 10:55:35</closed>
	</bug>
	<bug>
		<id>72</id>
		<title>SignerJar не может записать манифест.</title>
		<body>Подлежит фиксу по 1 возможности.</body>
		<created>2018-11-20 17:27:34</created>
		<closed>2018-11-25 17:35:46</closed>
	</bug>
	<bug>
		<id>13</id>
		<title>Фикс лагов с avn.</title>
		<body>Не знаю как, но сделать надо.</body>
		<created>2018-09-23 06:42:16</created>
		<closed>2018-09-23 12:26:54</closed>
	</bug>
	<bug>
		<id>2</id>
		<title>ZonaSumraka масса таких:</title>
		<body>EnotikСегодня в 18:10 @@administrator  помочь не хотите?? Exit code -1073741515 Exit code -1073741515 Exit code -1073741515 ???? </body>
		<created>2018-09-21 15:47:20</created>
		<closed>2018-09-21 15:55:40</closed>
	</bug>
</bugs>
